#!/bin/bash

echo "--------------------------------------"
echo "graphic package to display spindensity"
echo "--------------------------------------"
echo "arguments as for spindensplt:"
if test -f results/spindensplt.jvx
 then
  rm results/spindensplt.jvx
 fi
 
echo "# this is initial graphic parameters file" > results/graphic_parameters.set
while test -f results/graphic_parameters.set
do
spindensplt $*
if test -f results/spindensplt.jvx
then
java javaview results/spindensplt.jvx &
rem1=$!
java displaycontour 2 3 4 results/spindensplti.grid &
rem2=$!
java displaycontour 1 3 4 results/spindenspltj.grid &
rem3=$!
java displaycontour 1 2 4 results/spindenspltk.grid &
rem4=$!
java graphic_parameters_configurator 
kill $rem1
kill $rem2
kill $rem3
kill $rem4
else
  rm results/graphic_parameters.set 
fi
done




