#!/bin/bash

echo "--------------------------------------"
echo "graphic package to display current density"
echo "--------------------------------------"
echo "arguments as for currdensplt:"
if test -f  results/currdensplt.jvx
 then
  rm results/currdensplt.jvx
 fi

echo "# this is initial graphic parameters file" > results/graphic_parameters.set
while test -f results/graphic_parameters.set
do
  currdensplt $*
if test -f results/currdensplt.jvx
then
 java javaview results/currdensplt.jvx &
rem1=$!
java displaycontour 2 3 4 results/currdensplti.grid &
rem2=$!
 java displaycontour 1 3 4 results/currdenspltj.grid &
rem3=$!
java displaycontour 1 2 4 results/currdenspltk.grid &
rem4=$!
 java graphic_parameters_configurator 
kill $rem1
kill $rem2
kill $rem3
kill $rem4
else
  rm  results/graphic_parameters.set
fi
done

